name: Java CI with Maven

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
    
    - name: Set up JDK 12.0.2
      uses: actions/setup-java@v2
      with:
        java-version: '12.0.2'
        distribution: 'adopt'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file app/pom.xml

    - name: Unit test with Maven
      run: mvn -B package --file app/pom.xml

  
